name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency: # disable parallel workflow runs
      group: build-deploy
      cancel-in-progress: false
    container:
      image: ruby:2.7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build site
        id: image
        run: |
          bundle install
          bundle exec jekyll build

      - name: Checkout public branch
        uses: actions/checkout@v4
        with:
          ref: public
          path: public
          fetch-depth: 0

      - name: Copy build artifact
        run: |
          find public -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
          cp -R _site/. public/

      - name: Deploy site
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          cd public
          git config user.name "Stuart Sul"
          git config user.email "ssstuartss@gmail.com"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "${COMMIT_MSG}"
            git push origin public
          else
            echo "No changes to commit"
          fi
